### ISSUE TITLE
communities: organization list to render correct links and logos for edmo

### ISSUE THREAD

**Issue by 0einstein0** [inveniosoftware/invenio-communities#1254]

**Comment by ptamarit** [comment]
Tested both linked PRs with the `dump_only=True` suggested change on `invenio_vocabularies/contrib/affiliations/schema.py`.

The logo and links appear correctly, except in places where it was decided to not add it (since we do not want to add EDMO-specific code in APP-RDM):
- No EDMO logo/link deposit form
- No EDMO logo/link in the My Uploads screen
