### ISSUE TITLE
theme: fix header search 

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-communities#167]
The header search bar is not consistent

![image](https://user-images.githubusercontent.com/1698163/83397690-56b5d800-a3fe-11ea-838b-f120440420d0.png)

Should be like this:

![image](https://user-images.githubusercontent.com/1698163/83397709-5d444f80-a3fe-11ea-9b42-593e02cd2271.png)

**Comment by ppanero** [comment]
Findings from a quick investigation:

- invenio-communities has its own `header.html`
- it is needed because it needs to define certain urls to work
- Could it be solved by simple inheriting from `THEME_HEADER_TEMPLATE`? Therefore the `body_page` block would not be needed, just adding some jinja vars.
