### ISSUE TITLE
Uploading new picture before saving wipes out form 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-communities#741]
*from librarian testing*
Package version (if known): invenio-app-rdm 9.0.4 - invenio-communities 2.8.5

## Describe the bug
When creating a new community, entered descriptive text gets wiped out when the community picture is uploaded before the saved button is clicked. This happens systematically because this is how librarians traverse the form:

![picture_upload_wiping_out_text_detailed](https://user-images.githubusercontent.com/1932651/176900995-e8eb831a-2aff-4fae-8f57-e9f51160b7b4.png)
 
## Steps to Reproduce
1. Create a new community and get to the community settings page
2. Fill out the settings page from the top
3. Upload new picture before clicking on save
4. See filled out text be wiped out.

## Expected behavior
Uploading the picture before clicking on save should not wipe out the filled form.

**Comment by alejandromumo** [comment]
The issue here is that form's "Save" action is not tied with "File Upload" action.

We analysed whether we could bind these actions  together, but we did not find any reasonable solution in terms of UI/UX. We currently don't have a "draft" mode for community settings, so we can't replicate what we did in the upload form. Without a draft mode, we would need to submit the whole form when a logo is uploaded but it might not be transparent for the user that the whole form is going to be submitted when a logo is uploaded.

We discussed other possible solutions based on UI/UX only (e.g. notifying the user) but they do not fix the fundamental issue that is here described. We also fear that notifications could easily be oversighted by the user and ended up being ignored.

We are aware that this page has many UI / UX issues that were already identified and there are plans to improve it in the future. Such improvements might affect the way we deal with the settings as a whole and, therefore, we are going to wait until that time to also fix this issue.

**Comment by fenekku** [comment]
@alejandromumo thanks for following up on that.

I am not sure I follow the constraints laid out. I guess what I was thinking was either: 

1. Uploading a picture on this page changes the community logo immediately (maybe a modal before or a notification after to indicate this, but nothing would also be fine), but doesn't change the content of the form fields.

2. Uploading a picture doesn't change the community logo. It shows a preview by changing the displayed logo (maybe a modal before or a notification after or a watermark to indicate this, but nothing would also be fine), but doesn't change the content of the form fields. When clicking on Save, the form is saved and then the logo is saved (2 different API calls).

In neither case would (or should) we get the Draft resources mixed up in this :smile: . What am I missing here?
