### ISSUE TITLE
Request existing record to become part of community

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-communities#745]
*(I can't believe this is not a ticket already. I must have missed it somewhere, but I can't find it. So here we are)*

It should be possible to request for an existing published record (not already part of a community) to become part of a community.
This obviously needs mockups and flow investigation.

**Comment by ppanero** [comment]
+1 on this. Actually, this is possible in Zenodo.

I might be completely wrong, but isn't it already techincally feasible? However, we are not mapping correctly the `showCommunityHeader` and `showCommunitySelectionButton` [here](https://github.com/inveniosoftware/invenio-app-rdm/blob/bebc1d814238c16e0727c15d8c78b68878dd17bd/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js#L105) (or in the state) when we call "edit".

Maybe @zzacharo has more input.

P.S. I'm removing this from custom fields sprint because is not really something we can tackle since we already had to scope the custom fields themselves. I'm adding the "help wanted" tag, since it is important. Just in case someone else has time for it 👼 .

**Comment by fenekku** [comment]
In v12, thanks, closing.
