### ISSUE TITLE
Design new details sections on community details page

### ISSUE THREAD

**Issue by jennur** [inveniosoftware/invenio-communities#867]
Design and implement display of the data as new community tab(s) in InvenioRDM

Part 2 of https://github.com/inveniosoftware/invenio-communities/issues/861

**Comment by jennur** [comment]
## Suggested layout

- Curation policy goes in popup ([SUI popup](https://react.semantic-ui.com/modules/popup/)) in the community header
    - Should only be opened/closed by click
    - Need to make sure it is accessible
    - Props:
        - `trigger={<span><Icon name='info' circular /> Curation policy</span>}`
        - `wide`
        - `on="click"`
        - `position="bottom right"` on computer, `position="bottom left"` on tablet/mobile
 - "About this community" is moved from the header to a separate tab in the tab menu.
 - "Want your upload to appear in this community" instructions is present on every community's about page.

### Desktop
![Image](https://user-images.githubusercontent.com/21052053/214303349-8ffb6d6c-9e36-49fe-a7e5-2ef5f64a3522.png)
![Image](https://user-images.githubusercontent.com/21052053/214303350-5d55b736-cf5e-4f3b-a26a-6fcf1df6202e.png)

### Tablet
![Image](https://user-images.githubusercontent.com/21052053/214303956-c364ceee-d660-4eaa-953b-23ae0d7ecb35.png)

### Mobile
![Image](https://user-images.githubusercontent.com/21052053/214304801-e1853b1d-98d1-419a-bfb8-c38c58b38ca7.png)

**Comment by jennur** [comment]
## Curation policy in popup
- Curation policy goes in popup ([SUI popup](https://react.semantic-ui.com/modules/popup/)) in the community header
    - Should only be opened/closed by click
    - Need to make sure it is accessible
    - Props:
        - `trigger={<span><Icon name='info' circular /> Curation policy</span>}`
        - `wide`
        - `on="click"`
        - `position="bottom right"` on computer, `position="bottom left"` on tablet/mobile
 - Curation details (curator, created date, etc) is displayed below the custom about-text.
    - **Question:** Should we keep the curation policy here as well? (Maybe it's good to display it both places? LMK and I will add it to the mockup so that it reflects the popup content.)

![Image](https://user-images.githubusercontent.com/21052053/214303350-5d55b736-cf5e-4f3b-a26a-6fcf1df6202e.png)
![Image](https://user-images.githubusercontent.com/21052053/214303349-8ffb6d6c-9e36-49fe-a7e5-2ef5f64a3522.png)

**Comment by jennur** [comment]
## Curation policy in community footer
- Curation policy and details goes in a new community footer which is available on both the search page and the about page.
- The policy text should be truncated to not take up too much space
- On "Read more", the full text opens and expands the footer.


![version-2_search](https://user-images.githubusercontent.com/21052053/214328454-231b9d95-3d29-42e0-a7f8-c74c1220c76d.png)
![version-2_about_large-collapsed](https://user-images.githubusercontent.com/21052053/214328415-5ec75745-e340-48ab-bda3-8d5091d5c7b4.png)
![version-2_about_large](https://user-images.githubusercontent.com/21052053/214328418-4fbb2db1-5447-4569-a083-fc2746c500ee.png)

**Comment by kpsherva** [comment]
How about creating a separate tab for curation policy ?
I was told there are future plans to have the policy partially standarised by having checkboxes for commonly used policies, therefore it seems to me it is quite important part of the community -> maybe deserves a separate tab.
What do you think about combining it with the footer of community ? The "Read more" button would link to the tab instead expanding the footer.
I like the info being visible at all times in the footer, it keeps things visible

**Comment by jennur** [comment]
> How about creating a separate tab for curation policy ? I was told there are future plans to have the policy partially standarised by having checkboxes for commonly used policies, therefore it seems to me it is quite important part of the community -> maybe deserves a separate tab. What do you think about combining it with the footer of community ? The "Read more" button would link to the tab instead expanding the footer. I like the info being visible at all times in the footer, it keeps things visible

I will make another mockup so we can see! The only reason I'm not crazy about a separate tab for it, is if there might only be a single sentence (as is the case on many/most communities I've seen on Zenodo). Then it seems a bit overkill with a full dedicated page?

**Comment by slint** [comment]
I like the directions we're going towards in general. I have some other ideas (borrowing from GitHub and others), roughly described below.

#### Curation policy

- Separate tab for the Curation policy might make more sense in case they get big. In my mind it's similar to submission guidelines for a journal (i.e. as an author not the first thing you might be looking for when you land on the page, but it'll come to your mind eventually).
- Curation policy might get big/complex, so the pop-up can feel a bit too crowded and claustrophobic. If the curation policy includes information like "check out this document (link)" or "don't forget to include one of the keywords `ABC`, `DEF`, `XYZ`", the user will need to click and copy-paste the text, in which case the pop-up might feel a bit "flimsy". 
- Maybe we add a specific icon as well for a more distinct visual identity? Something related to rules/guidelines/policy (e.g. a hammer, law scales, stop-sign-hand?).

#### Other info (curator, OAI-PMH, etc.)

- Regarding the curator, since there might actually be multiple members with curation roles (some with public visibility, others not), I guess these should be displayed as a list of sorts (maybe similar to a GitHub repo's contributors?).
- The OAI-PMH harvesting link, feels a bit out of place (even in legacy Zenodo). There are two "entrypoints" for it:
  - the user knows they want to harvest via OAI-PMH, and are just looking for the exact link
  - the user wants to either receive updates/notifications or export all the records of a community. I think this hints towards a separate location, maybe closer to the community records search area, e.g. an "Export" dropdown at the bottom of the search results (or next to the sorting dropdown) a la GitHub's green "Code" dropdown that gives you the repo clone URI with a copy button.
- Created/Updated dates can maybe just be included in the "About" tab, on the top or bottom (similar to publication date or created/updated dates for the record landing page).

**Comment by jennur** [comment]
## Curator policy in separate tab
![version-3_about](https://user-images.githubusercontent.com/21052053/214575566-1212a49f-c8e9-41f0-be54-ca7cd17e60de.png)
![version-3_curation-policy](https://user-images.githubusercontent.com/21052053/214575571-a218d7a8-3c2c-42d1-a775-e3809fd4b793.png)

**Comment by jennur** [comment]
## Conclusion (discussed irl)

- Have the curation policy tab
- Keep the upload instructions section in both tabs (about, cur. pol.)
- Keep details in about page, below custom text

**Comment by jennur** [comment]
## Final mockups (Tabs)

### About
- Custom text content
- Details list
- Upload instructions

![version-3_about](https://user-images.githubusercontent.com/21052053/215730865-622da3aa-4633-4359-83c1-891640bd3f1c.png)

### Curation policy
- Custom text content
- Upload instructions

![version-3_curation-policy](https://user-images.githubusercontent.com/21052053/215730873-bbeec31f-113b-4596-adbd-a55a1e3d3242.png)

**Comment by RosaLo** [comment]
Since I'm also being a curator of a community at zenodo. I appreciate that the curation policy is clearly visible for users so they understand it.  We have also discussed that it would be good if the curation policy is more visible to a user when that user submits data to the community. Now, in Invenio, a user can  select communities from a list - I think it would be nice to have the option to get more info about a community unfolding in the list WHEN selecting community 

![Image](https://user-images.githubusercontent.com/35691320/216271362-3c2f6c94-467e-4192-aeb4-d74e1857d332.png)

**Comment by jennur** [comment]
> Since I'm also being a curator of a community at zenodo. I appreciate that the curation policy is clearly visible for users so they understand it. We have also discussed that it would be good if the curation policy is more visible to a user when that user submits data to the community. Now, in Invenio, a user can select communities from a list - I think it would be nice to have the option to get more info about a community unfolding in the list WHEN selecting community

Thank you for your feedback!! We are actually already considering this, it will be part of a different task! :)
